-- Copiando estrutura do banco de dados para basesgmasteralpes
CREATE DATABASE IF NOT EXISTS `basesgmasteralpes` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `basesgmasteralpes`;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER DELETE TITEMCOMPRA_AD0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER DELETE TITEMCOMPRA_AD0` AFTER DELETE ON `titemcompra` FOR EACH ROW BEGIN

	if (old.CONFIRMADO = 'SIM') then
		CALL spatualizaqtde(old.codproduto);
   END if;
   
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER DELETE TITEMCOMPRA_AD1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER DELETE TITEMCOMPRA_AD1` AFTER DELETE ON `titemcompra` FOR EACH ROW BEGIN

	if (old.CONFIRMADO = 'SIM') then
   	CALL spatualizadataestoque(old.codproduto);
   END if;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER DELETE TITEMPEDIDOVENDA_AD0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER DELETE TITEMPEDIDOVENDA_AD0` AFTER DELETE ON `titempedidovenda` FOR EACH ROW BEGIN

    CALL spatualizaqtde(old.codproduto);
    CALL sptotalizapedidovenda(old.codpedidovenda);
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER INSERT TORDEMPRODUCAO_DESMEMBRAMENTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER INSERT TORDEMPRODUCAO_DESMEMBRAMENTO` AFTER INSERT ON `tordemproducao` FOR EACH ROW BEGIN

    if (new.CODDESMEMBRAMENTO is not null) then
        CALL SPALIMENTAITEMDESMEMBRAMENTO(new.CONTROLE, new.CODDESMEMBRAMENTO);
    END IF;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TACOUGUEDES_AJUSTEESTOQUE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TACOUGUEDES_AJUSTEESTOQUE` AFTER UPDATE ON `tacouguedesmembramento` FOR EACH ROW BEGIN

    if (new.STATUS = '2')  then
        CALL spcriaopdesmembramento(new.CONTROLE);
        CALL spajustaqtdedesmembramento(new.CONTROLE);
    END IF;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TESTOQUE_ALTERACAOPRECO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TESTOQUE_ALTERACAOPRECO` AFTER UPDATE ON `testoque` FOR EACH ROW BEGIN

	if (new.PRECOVENDA <> old.PRECOVENDA) then
        INSERT INTO TESTOQUEHISTORICO (CODPRODUTO, PRECOANTIGO, PRECONOVO) VALUES (new.CONTROLE, old.PRECOVENDA, new.PRECOVENDA);
	END if;
	
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TGRADE_BU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TGRADE_BU0` AFTER UPDATE ON `tgrade` FOR EACH ROW BEGIN
	
    if ((new.quantidade <> old.quantidade) and (new.tpalteracao = '1')) then
    
        INSERT INTO TAJUSTEESTOQUEGRADE (CODPRODUTO, CODGRADE, QTDEALTERADA, QTDEANTERIOR, QTDENOVA)
                                    VALUES
                                        (new.codproduto, new.controle, (new.quantidade - old.quantidade), old.quantidade, new.quantidade);
                                        
	
    END IF; 
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TITEMCOMPRA_AU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TITEMCOMPRA_AU0` AFTER UPDATE ON `titemcompra` FOR EACH ROW BEGIN

	DECLARE CODGRADE, DONE INT DEFAULT 0;
   DECLARE SQLGRADE CURSOR FOR select COG.CODGRADE from TITEMCOMPRAGRADE COG where COG.CODITEMCOMPRA = new.CONTROLE and COG.CODCOMPRA = new.CODCOMPRA;
   DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
   
	if ((new.CONFIRMADO = 'SIM') and (new.MOVIMENTAESTOQUE <> '')) then
    
		call SPATUALIZAQTDE(new.CODPRODUTO);
	   
	   if (new.USAGRADE = 'SIM') then
	      OPEN SQLGRADE;
	      
			LoopGrade : Loop
				Fetch SQLGRADE INTO CODGRADE;							
				if DONE = TRUE then
					leave LoopGrade;
				END if;
		   	call SPATUALIZAQTDEGRADE(new.CODPRODUTO, CODGRADE);				
				SET CODGRADE = 0;		   	
			END loop LoopGrade;
					   
	      CLOSE SQLGRADE;			
	      
		END if;
	   
	END if;
	
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TITEMCOMPRA_AU1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TITEMCOMPRA_AU1` AFTER UPDATE ON `titemcompra` FOR EACH ROW BEGIN

	if ((new.CONFIRMADO = 'SIM') and (new.MOVIMENTAESTOQUE <> '')) then
   	call spatualizadataestoque(new.CODPRODUTO);
	END if;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TITEMPEDIDOVENDA_AIU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TITEMPEDIDOVENDA_AIU0` AFTER INSERT ON `titempedidovenda` FOR EACH ROW begin
    CALL sptotalizapedidovenda(new.codpedidovenda);
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TITEMPEDIDOVENDA_AU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TITEMPEDIDOVENDA_AU0` AFTER UPDATE ON `titempedidovenda` FOR EACH ROW BEGIN

    CALL sptotalizapedidovenda(new.codpedidovenda);

    CALL spatualizaqtde(new.codproduto);
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TNOTACONSUMIDOR_STATUSCOMANDA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TNOTACONSUMIDOR_STATUSCOMANDA` AFTER UPDATE ON `tnotaconsumidor` FOR EACH ROW BEGIN

	if ((new.codmodulo is not null) and (new.modulo = 'COMANDAS')) then
   
   	if ((new.DATAFATURADA is not NULL) OR (new.JAFATURADA = 'NÃO')) then      
        
   		CALL spatualizastatuscomanda(new.codmodulo);
		Delete from tcomandaagrupada where tcomandaagrupada.codmodulo = new.CONTROLE and tcomandaagrupada.origem = 'NOTA MANUAL';			           
			
      END IF;
        
	END IF;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TOS_AIU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TOS_AIU0` AFTER UPDATE ON `tos` FOR EACH ROW BEGIN

	if (new.situacao <> old.situacao) then
   	CALL spatualizastatusitemos(new.controle, new.situacao);
	END if;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.AFTER UPDATE TVENDANFCE_STATUSCOMANDA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AFTER UPDATE TVENDANFCE_STATUSCOMANDA` AFTER UPDATE ON `tvendanfce` FOR EACH ROW BEGIN

	if ((new.CODCOMANDA IS NOT NULL) AND 
		(((new.CODIGOSTATUS = 6000) OR ((Trim(new.PROTOCOLO) <> '') AND
   	(new.PROTOCOLO IS NOT NULL) AND (new.SAT <> 'SIM'))) AND
      ((new.PROTOCOLOCANCELAMENTO IS NULL) OR (Trim(new.PROTOCOLOCANCELAMENTO) = '')))) then
      
      	CALL spatualizastatuscomanda(new.codcomanda);
		Delete from tcomandaagrupada where tcomandaagrupada.codmodulo = new.CONTROLE and tcomandaagrupada.origem = if(new.SAT <> 'SIM', 'NFCE', 'SAT');      
      
	END IF;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE DELETE TCOMANDAAGRUPADA_STATUSCOMANDA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE DELETE TCOMANDAAGRUPADA_STATUSCOMANDA` BEFORE DELETE ON `tcomandaagrupada` FOR EACH ROW BEGIN

	DECLARE TOTAL INTEGER DEFAULT 0;
	
    if ((old.CODCOMANDA is not null) and (old.CODMODULO is not null)) then	
	
        if  ((old.ORIGEM = 'NFCE') or (old.ORIGEM = 'SAT')) then

            SELECT COUNT(CONTROLE) AS TT INTO @TOTAL FROM TVENDANFCE WHERE CONTROLE = old.CODMODULO
                                                    AND ((CODIGOSTATUS = 6000) or
                                                    (((Trim(PROTOCOLO) <> '') AND (PROTOCOLO IS NOT NULL)) AND (SAT <> 'SIM')));
            if (@TOTAL > 0) then
                CALL spatualizastatuscomanda(old.CODCOMANDA);
            END IF;

        END IF;

        if  (old.ORIGEM = 'NOTA MANUAL') then

            SELECT COUNT(CONTROLE) AS TT INTO @TOTAL FROM TNOTACONSUMIDOR WHERE CONTROLE = old.CODMODULO AND ((JAFATURADA = 'NÃO') or (DATAFATURADA IS NOT NULL));
            if (@TOTAL > 0) then
                CALL spatualizastatuscomanda(old.CODCOMANDA);
            END IF;

        END IF; 

    END IF;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE DELETE TGRADE_BD0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE DELETE TGRADE_BD0` BEFORE DELETE ON `tgrade` FOR EACH ROW BEGIN

    Delete from tajusteestoquegrade where codgrade = old.controle;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE DELETE TGRADE_BD1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE DELETE TGRADE_BD1` BEFORE DELETE ON `TGRADE` FOR EACH ROW BEGIN
	DECLARE data VARCHAR(50);
	
	SET data = concat('{"codsgmaster":"', OLD.controle, '"}');	
	
	if (old.md5s is not null) then
   	INSERT INTO ttransmissaows(destino, tipo, dados) values ('S', 'GRADE', data);
	END if;
	
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE DELETE TPARCPREDINTERVALO_BD0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE DELETE TPARCPREDINTERVALO_BD0` BEFORE DELETE ON `tparcelapredefinidaintervalo` FOR EACH ROW BEGIN
	DECLARE data VARCHAR(50);
	
	SET data = concat('{"codsgmaster":"', OLD.controle, '"}');	
	
	if (old.md5o is not null) then
   	INSERT INTO ttransmissaows(destino, tipo, dados) values ('P', 'PARCPREDIN', data);
	END if;
	
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE INSERT TITEMVENDANFCE_CALCULADESCONTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE INSERT TITEMVENDANFCE_CALCULADESCONTO` BEFORE INSERT ON `titemvendanfce` FOR EACH ROW BEGIN
    DECLARE  calculou SMALLINT;
    DECLARE  precominimo NUMERIC(15,4);
    DECLARE  valorunitario NUMERIC(15,4);
    SET valorunitario = new.valorunitario;
  	 SET calculou = 0;
  	 
		select precominimo from testoque where controle = NEW.codproduto 
			into precoMinimo;   	
   	if (precoMinimo > 0 and new.brinde <> '1') then
        	if new.valorunitario < precominimo then
            SET new.valorunitario = valorunitario;
         END IF;
      END IF;     
	  if ((new.valordescontoitem  > 0) and (new.valordescontoitem is not null)) then
	    SET New.percdescontoitem = 0;
	    SET New.percdescontoitem = 100 * (coalesce(New.valordescontoitem,0) / coalesce(New.valortotal,0));
	    SET calculou = 1;
		END IF;
	  if (calculou = 0) then
	    if ((new.PERCDESCONTOITEM > 0) and (new.PERCDESCONTOITEM is not null)) then
	        SET New.valordescontoitem = 0;
	        SET New.valordescontoitem = (coalesce(New.valortotal,0)  / 100)* coalesce(Truncate(New.percdescontoitem,2),0);
	    END IF;
	  END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE INSERT TITEMVENDANFCE_VALIDACFOP
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE INSERT TITEMVENDANFCE_VALIDACFOP` BEFORE INSERT ON `titemvendanfce` FOR EACH ROW BEGIN
    DECLARE cfop VARCHAR(4);
    SET cfop = NEW.cfop;
    if (SUBSTRING( cfop FROM 1 FOR 1) <> '5') then
        SET cfop = CONCAT('5', SUBSTRING(cfop, 2));
        SET NEW.cfop = cfop;
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TCLIENTE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TCLIENTE` BEFORE UPDATE ON `tcliente` FOR EACH ROW BEGIN
		if (NEW.CLIENTE <> OLD.CLIENTE) OR (NEW.RG <> OLD.RG) OR (NEW.CPF <> OLD.CPF) or
			(NEW.CNPJ <> OLD.CNPJ) OR (NEW.TELEFONE <> OLD.TELEFONE) OR (NEW.CELULAR <> OLD.CELULAR) or
			(NEW.EMAIL <> OLD.EMAIL) OR (NEW.LIMITECREDITO <> OLD.LIMITECREDITO) OR (NEW.FANTASIA <> OLD.FANTASIA) OR 
			(NEW.ENDERECO <> OLD.ENDERECO) OR (NEW.BAIRRO <> OLD.BAIRRO) OR (NEW.COMPLEMENTO <> OLD.COMPLEMENTO) OR
			(NEW.NUMERO <> OLD.NUMERO) OR (NEW.UF <> OLD.UF) OR (NEW.CIDADE <> OLD.CIDADE) OR (NEW.CEP <> OLD.CEP) THEN
			 SET NEW.SINCRONIZADO = '0';
		END if;	
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TEMITENTE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TEMITENTE` BEFORE UPDATE ON `temitente` FOR EACH ROW BEGIN
		IF (NEW.NOMEFANTASIA <> OLD.NOMEFANTASIA) OR (NEW.RAZAOSOCIAL <> OLD.RAZAOSOCIAL) OR
			(NEW.ENDERECO <> OLD.ENDERECO) OR (NEW.COMPLEMENTO <> OLD.COMPLEMENTO) OR
			(NEW.BAIRRO <> OLD.BAIRRO) OR (NEW.CODCIDADE <> OLD.CODCIDADE) OR
			(NEW.UF <> OLD.UF) OR (NEW.CEP <> NEW.CEP) OR (NEW.TELEFONE <> OLD.TELEFONE) OR 
			(NEW.CELULAR <> OLD.CELULAR) OR (NEW.EMAIL <> OLD.EMAIL) OR (NEW.CNAE <> OLD.CNAE) OR 
			(NEW.CRT <> OLD.CRT) THEN
			 SET NEW.SINCRONIZADO = '0';
		END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TESPECIE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TESPECIE` BEFORE UPDATE ON `tespecie` FOR EACH ROW BEGIN
		if (NEW.ESPECIE <> OLD.ESPECIE) OR (NEW.TIPOLANCAMENTOFINANCEIRO <> OLD.TIPOLANCAMENTOFINANCEIRO) or
			(NEW.TECLAFINALIZACAORAPIDA <> OLD.TECLAFINALIZACAORAPIDA) OR (NEW.ORDEMAPRESENTACAO <> OLD.ORDEMAPRESENTACAO) or
			(NEW.DEBITOAVISTA <> OLD.DEBITOAVISTA) OR (NEW.CREDITOAVISTA <> OLD.CREDITOAVISTA) OR (NEW.CREDITOPARCELADO <> OLD.CREDITOPARCELADO) or
			(NEW.TIPOCARTAO <> OLD.TIPOCARTAO) OR (NEW.NFCE <> OLD.NFCE) or (NEW.ASSOCIACAONFCE <> OLD.ASSOCIACAONFCE) OR (NEW.CREDITOCLIENTE <> OLD.CREDITOCLIENTE) OR
			(NEW.QTDEPARCELA <> OLD.QTDEPARCELA) OR (NEW.QTDEPARCELAPADRAO <> OLD.QTDEPARCELAPADRAO) OR (NEW.PERCJURO <> OLD.PERCJURO) OR 
			(NEW.DIASINTERVALOPADRAO <> OLD.DIASINTERVALOPADRAO) then
			SET NEW.sincronizado = '0';		
		END if;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TESTOQUE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TESTOQUE` BEFORE UPDATE ON `testoque` FOR EACH ROW BEGIN
		if (NEW.PRODUTO <> OLD.PRODUTO) OR (NEW.CODBARRAS <> OLD.CODBARRAS) or
			(NEW.NCM <> OLD.NCM) OR (NEW.REFERENCIA <> OLD.REFERENCIA) OR 
			(NEW.PERCIMPOSTOMEDIO <> OLD.PERCIMPOSTOMEDIO) OR 
			(NEW.PERCIMPOSTOMEDIOESTADUAL <> OLD.PERCIMPOSTOMEDIOESTADUAL) OR
			(NEW.PERCIMPOSTOMEDIOMUNICIPAL <> OLD.PERCIMPOSTOMEDIOMUNICIPAL) OR
			(NEW.MARCA <> OLD.MARCA) OR (NEW.CODTABELAPRECO <> OLD.CODTABELAPRECO) OR
			(NEW.CSOSN <> OLD.CSOSN) OR (NEW.CFOP <> OLD.CFOP) OR (NEW.CODIGOANP <> OLD.CODIGOANP) OR
			(NEW.CODIGOANVISA <> OLD.CODIGOANVISA) OR (NEW.CODTRIBUTACAOIPI <> OLD.CODTRIBUTACAOIPI) OR
			(NEW.PERCIPI <> OLD.PERCIPI) OR (NEW.CODIGOENQUADRAMENTOIPI <> OLD.CODIGOENQUADRAMENTOIPI) OR 
			(NEW.SELOIPI <> OLD.SELOIPI) OR (NEW.CODTRIBUTACAOPIS <> OLD.CODTRIBUTACAOPIS) OR
			(NEW.CODTRIBUTACAOCOFINS <> OLD.CODTRIBUTACAOCOFINS) OR (NEW.PERCCOFINS <> OLD.PERCCOFINS) OR 
			(NEW.UNIDADE <> OLD.UNIDADE) OR (NEW.PRECOVENDA <> old.PRECOVENDA) or 
			(NEW.ATIVO <> OLD.ATIVO) OR (NEW.NCM <> OLD.NCM) or 
			(NEW.CODGRUPO <> OLD.CODGRUPO) OR (NEW.CODBARRASCAIXA <> OLD.CODBARRASCAIXA) or
			(NEW.PESADO <> OLD.PESADO) OR (NEW.IPPT <> OLD.IPPT) OR (NEW.VALORCONVERSAOVENDA <> OLD.VALORCONVERSAOVENDA) or
			(NEW.UNIDADECONVERSAOVENDA <> OLD.UNIDADECONVERSAOVENDA) OR (NEW.PERCDESCONTOCAIXA <> OLD.PERCDESCONTOCAIXA) or
			(NEW.CODBARRASINTERNO <> old.CODBARRASINTERNO) OR (NEW.USAGRADE <> OLD.USAGRADE) or
			(NEW.USASERIAL <> OLD.USASERIAL) OR (NEW.CONTROLARVALIDADE <> OLD.CONTROLARVALIDADE) then
			SET new.sincronizado = '0';
		END IF;
	END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TFORMAPAGAMENTONOTAMANUAL_BU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TFORMAPAGAMENTONOTAMANUAL_BU0` BEFORE UPDATE ON `tformapagamentonotamanual` FOR EACH ROW begin
   DECLARE pagocliente, pagoucliente, totalnota, troco, totaltroco DECIMAL(15,2) DEFAULT 0;
   DECLARE creditotroco CHAR(1);
	DECLARE DONE INT DEFAULT 0;
   DECLARE SQLPAGOCLIENTE CURSOR FOR select cast(replace(new.valorpagovarchar,',','.') as DECIMAL(15,2)) from tformapagamentonotamanual fp 
											WHERE  fp.codnotamanual = new.codnotamanual and fp.controle = new.controle;
   DECLARE SQLPAGOUCLIENTE CURSOR FOR select sum(coalesce(f.valorpago,0)) from tformapagamentonotamanual f 
											where f.codnotamanual = new.codnotamanual and f.controle <> new.controle;	
	DECLARE SQLTOTALNOTA CURSOR FOR select nc.totalnota from tnotaconsumidor nc where nc.controle = new.codnotamanual;
	DECLARE SQLCREDITOTROCO CURSOR FOR SELECT new.creditotroco FROM tformapagamentonotamanual tf WHERE tf.codnotamanual = new.codnotamanual and tf.controle = new.controle;
   DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;											

	OPEN SQLCREDITOTROCO;
   FETCH SQLCREDITOTROCO INTO creditotroco;
   CLOSE SQLCREDITOTROCO;
   
    if (creditotroco <> '1' and cast(replace(new.valorpagovarchar,',','.') as DECIMAL(15,2)) > 0) then                         
        
		   OPEN SQLPAGOCLIENTE;
	      
			LOOPFORMAPAGAMENTO : Loop
				Fetch SQLPAGOCLIENTE INTO pagocliente;							
				if DONE = TRUE then
					leave LOOPFORMAPAGAMENTO;
				END if;				
			END loop LOOPFORMAPAGAMENTO;
					   
	      CLOSE SQLPAGOCLIENTE;
                

	      OPEN SQLPAGOUCLIENTE;
		      
			LOOPFORMAPAGAMENTO : Loop
				Fetch SQLPAGOUCLIENTE INTO pagoucliente;							
				if DONE = TRUE then
					leave LOOPFORMAPAGAMENTO;
				END if;	   	
			END loop LOOPFORMAPAGAMENTO;
					   
	      CLOSE SQLPAGOUCLIENTE;
	      
        	OPEN SQLTOTALNOTA;
        	
			LOOPFORMAPAGAMENTO : Loop
				Fetch SQLTOTALNOTA INTO totalnota;							
				if DONE = TRUE then
					leave LOOPFORMAPAGAMENTO;
				END if;	   	
			END loop LOOPFORMAPAGAMENTO;
					   
	      CLOSE SQLTOTALNOTA;
	      
         if ((pagoucliente + pagocliente) > totalnota) then
             SET troco = (pagoucliente + pagocliente) - totalnota;
             SET new.valortroco = troco;
             SET totaltroco = totaltroco + troco;
         else
             SET troco = 0;
             SET new.valortroco = troco;
         END IF;
         
         if (new.valortroco > 0) then
            SET new.valorpago = pagocliente - new.valortroco;
         END if;
         
         if (new.valorpago < 0 ) then
             SET new.valortroco = 0;
             SET new.valorpago = pagocliente;
         END if;
    END if;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TFUNCIONARIO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TFUNCIONARIO` BEFORE UPDATE ON `tfuncionario` FOR EACH ROW BEGIN
	if (NEW.FUNCIONARIO <> OLD.FUNCIONARIO) OR (NEW.RG <> OLD.RG) OR (NEW.CPF <> OLD.CPF) then
		SET NEW.SINCRONIZADO = '0';
	END if;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TIMPOSTOMEDIO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TIMPOSTOMEDIO` BEFORE UPDATE ON `timpostomedio` FOR EACH ROW BEGIN
	if (NEW.NCMNBS <> OLD.NCMNBS) OR (NEW.EXCECAOFISCAL <> OLD.EXCECAOFISCAL) OR 
		(NEW.DESCRICAO <> OLD.DESCRICAO) OR (NEW.EPRODUTO <> OLD.EPRODUTO ) or
		(NEW.ALIQUOTANACIONAL <> OLD.ALIQUOTANACIONAL) OR (NEW.ALIQUOTAESTADUAL <> OLD.ALIQUOTAESTADUAL) OR
		(NEW.ALIQUOTAMUNICIPAL <> OLD.ALIQUOTAMUNICIPAL) OR (NEW.CEST <> OLD.CEST) or
		(NEW.ATIVO <> OLD.ATIVO) then
		 SET NEW.SINCRONIZADO = '0';
	END if;			
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TITEMCONTAGEMESTOQUE_BU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TITEMCONTAGEMESTOQUE_BU0` BEFORE UPDATE ON `titemcontagemestoque` FOR EACH ROW BEGIN

	if (new.qtdecontada <> old.qtdecontada) then       
	
		SET new.qtdeajustar = new.qtdecontada - new.qtdeatual;
		if (new.qtdeajustar < 0) then
			SET new.valorajustado = (new.qtdeajustar * new.precocusto)*-1;
			SET new.valorajustado = new.valorajustado * -1;
		END IF;
		if (new.qtdeajustar >= 0) then
			SET new.valorajustado = new.qtdeajustar * new.precocusto;
			SET new.valorajustado = new.qtdeajustar * new.precocusto;
		END IF;
		
	END if;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TITEMVENDANFCE_CALCULADESCONTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TITEMVENDANFCE_CALCULADESCONTO` BEFORE UPDATE ON `titemvendanfce` FOR EACH ROW BEGIN
    DECLARE  calculou SMALLINT;
    DECLARE  precominimo NUMERIC(15,4);
    DECLARE  valorunitario NUMERIC(15,4);
    SET valorunitario = new.valorunitario;
  	 SET calculou = 0;
  	 
		select precominimo from testoque where controle = NEW.codproduto 
			into precoMinimo;   	
   	if (precoMinimo > 0 and new.brinde <> '1') then
        	if new.valorunitario < precominimo then
            SET new.valorunitario = valorunitario;
         END IF;
      END IF;     
	  if ((new.valordescontoitem  > 0) and (new.valordescontoitem is not null)) then
	    SET New.percdescontoitem = 0;
	    SET New.percdescontoitem = 100 * (coalesce(New.valordescontoitem,0) / coalesce(New.valortotal,0));
	    SET calculou = 1;
		END IF;
	  if (calculou = 0) then
	    if ((new.PERCDESCONTOITEM > 0) and (new.PERCDESCONTOITEM is not null)) then
	        SET New.valordescontoitem = 0;
	        SET New.valordescontoitem = (coalesce(New.valortotal,0)  / 100)* coalesce(Truncate(New.percdescontoitem,2),0);
	    END IF;
	  END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TITEMVENDANFCE_TOTALIZAITEM
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TITEMVENDANFCE_TOTALIZAITEM` BEFORE UPDATE ON `titemvendanfce` FOR EACH ROW BEGIN
	declare  VALORANTES numeric(15,2);
	declare  QTDEANTES numeric(15,4);	
	
   SET VALORANTES = 0;
   SET QTDEANTES = 0;
   SET VALORANTES = old.VALORUNITARIO;
   SET QTDEANTES = old.QTDE;
   
   if (new.QTDE is null) then
     set new.QTDE = '1';
   END IF;
   
   if ((cast(new.VALORUNITARIO as varchar(15)) is null) or (cast(new.VALORUNITARIO as varchar(15)) < 0.001) and (new.brinde <> '1')) then
     SET new.VALORUNITARIO = VALORANTES;
   END IF;
   
   if ((cast(new.QTDE as varchar(15)) is null) or (cast(new.QTDE as varchar(15)) < 0.001)) then
      set new.QTDE = QTDEANTES;
   END IF;
   
   SET new.VALORTOTAL = cast((new.VALORUNITARIO) * (cast(new.QTDE as decimal(15,4))) as decimal(15,2));
   SET new.VALORLIQUIDO = coalesce(new.VALORTOTAL, 0) - coalesce(new.VALORDESCONTO, 0) - coalesce(new.VALORDESCONTOITEM, 0) + coalesce(new.VALORACRESCIMO, 0) + coalesce(new.VALORSEGURO, 0) + coalesce(new.VALORICMSST, 0) + coalesce(new.VALOROUTROS, 0) + coalesce(new.VALOROUTROSITEM, 0);
   SET new.VALORIMPOSTOMEDIO = if(((coalesce(new.VALORLIQUIDO, 0) * coalesce((select PERCIMPOSTOMEDIO from TESTOQUE where CONTROLE = new.CODPRODUTO), 0)) / 100) > 0, 
                            ((coalesce(new.VALORLIQUIDO, 0) * coalesce((select PERCIMPOSTOMEDIO from TESTOQUE where CONTROLE = new.CODPRODUTO), 0)) / 100), 0);
                            
   if ((new.CSOSN = 00) or (new.CSOSN = 0) or (new.CSOSN = 20) or (new.CSOSN = 90)) then
      if (coalesce(new.PERCICMS, 0) > 0) then
         if (coalesce(new.percreducaobc, 0) > 0) then
            set new.VALORBCICMS = cast(new.VALORLIQUIDO as decimal(15,4)) * (1 - (new.percreducaobc / 100));
         ELSE
            set new.VALORBCICMS = cast(new.VALORLIQUIDO as decimal(15,4));
            
         set new.VALORICMS = ((cast(new.VALORBCICMS as decimal(15,4)) / 100) * coalesce(new.PERCICMS, 0));
         END if;
      END if;
   END if;
   
   if ((new.CFOP = '5933') AND (new.CSOSN is null)) then
      if (coalesce(new.VALORALIQUOTAISSQN, 0) > 0) then
         set new.VALORBCISSQN = cast(new.VALORLIQUIDO as decimal(15,4));
         set new.VALORISSQN = ((cast(new.VALORBCISSQN as decimal(15,4)) / 100) * coalesce(new.VALORALIQUOTAISSQN, 0));
      END if;
   END if;
   set new.VALORBCPIS = cast(new.VALORLIQUIDO as decimal(15,4));
   set new.VALORPIS = ((cast(new.VALORBCPIS as decimal(15,4)) / 100) * coalesce(new.PERCPIS, 0));
   set new.VALORBCCOFINS = cast(new.VALORLIQUIDO as decimal(15,4));
   set new.VALORCOFINS = ((cast(new.VALORBCCOFINS as decimal(15,4)) / 100) * coalesce(new.PERCCOFINS, 0));

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TITENNOTACONSUMIDOR_BIU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TITENNOTACONSUMIDOR_BIU0` BEFORE UPDATE ON `titennotaconsumidor` FOR EACH ROW
BEGIN
    DECLARE precominimo DECIMAL(15,4);
    DECLARE valorantes DECIMAL(15,4);
    DECLARE qtdeantes DECIMAL(15,4); 
    
    SET valorantes = 0;
    SET qtdeantes = 0;
    
    IF OLD.precounitario IS NOT NULL THEN
        SET valorantes = OLD.precounitario;
    END IF;
    
    IF OLD.qtde IS NOT NULL THEN
        SET qtdeantes = OLD.qtde;
    END IF;
    
    IF (NEW.precounitario IS NULL OR NEW.precounitario < 0.001) AND NEW.brinde <> '1' THEN
        SET NEW.precounitario = valorantes;
    END IF;
    
    IF (NEW.qtde IS NULL OR NEW.qtde < 0.001) THEN
        SET NEW.qtde = qtdeantes;
    END IF;
    
    SELECT COALESCE(precominimo, 0) INTO precominimo
    FROM testoque
    WHERE controle = NEW.codproduto;
    
    IF precominimo > 0 AND NEW.precounitario < precominimo THEN
        SET NEW.precounitario = OLD.precounitario;
    END IF;
    
    SET NEW.TOTALITENS = NEW.PRECOUNITARIO * NEW.QTDE;
    SET NEW.TOTALIQUIDO = NEW.TOTALITENS - COALESCE(NEW.VALORDESCONTO, 0) + COALESCE(NEW.VALORACRESCIMO, 0);
    
    IF NEW.CSOSN <> '' THEN
        IF NEW.CSOSN IN ('00', '0', '20', '90') THEN
            SET NEW.VALORBASECALCULO = NEW.TOTALIQUIDO;
            SET NEW.VALORICMS = (NEW.VALORBASECALCULO / 100) * COALESCE(NEW.PERCICMS, 0);
        END IF;
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TPEDIDOIFOOD_01
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TPEDIDOIFOOD_01` BEFORE UPDATE ON `tpedidoifood` FOR EACH ROW BEGIN

	if (new.status <> old.status) then
		set new.datahoraalterastatus = Current_Timestamp;
	END if;
	
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TPROMOCAO SINCRONIZADO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TPROMOCAO SINCRONIZADO` BEFORE UPDATE ON `tpromocao` FOR EACH ROW BEGIN

    if ((new.precovenda <> old.precovenda) or
        (new.tipo <> old.tipo) or
        (new.periodo <> old.periodo) or
        (new.datainicio <> old.datainicio) or
        (new.datafinal <> old.datafinal) or
        (new.qtde <> old.qtde)) then
        set new.sincronizado = '0';
    END if;
    
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE UPDATE TTABELAPRECO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE UPDATE TTABELAPRECO` BEFORE UPDATE ON `ttabelapreco` FOR EACH ROW BEGIN
	if (NEW.NOMETABELA <> OLD.NOMETABELA) OR (NEW.DATAINICIAL <> OLD.DATAINICIAL) or
		(NEW.DATAFINAL <> OLD.DATAFINAL) OR (NEW.ATIVO <> OLD.ATIVO) OR (NEW.PERCDESCONTO <> OLD.PERCDESCONTO) or
		(NEW.PERCACRESCIMO <> OLD.PERCACRESCIMO) OR (NEW.EXPIRADO <> OLD.EXPIRADO) OR (NEW.TIPO <> OLD.TIPO) then
		 SET NEW.SINCRONIZADO = '0';
	END if;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BEFORE_UPDATE_TITEMVENDANFCE_TOTALIZAITEM
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFORE_UPDATE_TITEMVENDANFCE_TOTALIZAITEM`
BEFORE UPDATE ON `titemvendanfce`
FOR EACH ROW
BEGIN
   DECLARE VALORANTES DECIMAL(15,2);
   DECLARE QTDEANTES DECIMAL(15,4);    
   DECLARE EXCLUIBCPISCOFINS CHAR(1);
   
   SET VALORANTES = OLD.VALORUNITARIO;
   SET QTDEANTES = OLD.QTDE;
   SET EXCLUIBCPISCOFINS = NEW.EXCLUSAOICMSPC;
   
   IF (NEW.QTDE IS NULL) THEN
     SET NEW.QTDE = 1;
   END IF;
   
   IF ((CAST(NEW.VALORUNITARIO AS CHAR) IS NULL) OR (NEW.VALORUNITARIO < 0.001) AND (NEW.BRINDE <> '1')) THEN
     SET NEW.VALORUNITARIO = VALORANTES;
   END IF;
   
   IF ((CAST(NEW.QTDE AS CHAR) IS NULL) OR (NEW.QTDE < 0.001)) THEN
      SET NEW.QTDE = QTDEANTES;
   END IF;
   
   SET NEW.VALORTOTAL = CAST(NEW.VALORUNITARIO * CAST(NEW.QTDE AS DECIMAL(15,4)) AS DECIMAL(15,2));
   SET NEW.VALORLIQUIDO = COALESCE(NEW.VALORTOTAL, 0) - COALESCE(NEW.VALORDESCONTO, 0) - COALESCE(NEW.VALORDESCONTOITEM, 0) + COALESCE(NEW.VALORACRESCIMO, 0) + COALESCE(NEW.VALORSEGURO, 0) + COALESCE(NEW.VALORICMSST, 0) + COALESCE(NEW.VALOROUTROS, 0) + COALESCE(NEW.VALOROUTROSITEM, 0);
   SET NEW.VALORIMPOSTOMEDIO = IF(((COALESCE(NEW.VALORLIQUIDO, 0) * COALESCE((SELECT PERCIMPOSTOMEDIO FROM TESTOQUE WHERE CONTROLE = NEW.CODPRODUTO), 0)) / 100) > 0, 
                            ((COALESCE(NEW.VALORLIQUIDO, 0) * COALESCE((SELECT PERCIMPOSTOMEDIO FROM TESTOQUE WHERE CONTROLE = NEW.CODPRODUTO), 0)) / 100), 0);
                            
   IF ((NEW.CSOSN = '00') OR (NEW.CSOSN = '0') OR (NEW.CSOSN = '20') OR (NEW.CSOSN = '90')) THEN
      IF (COALESCE(NEW.PERCICMS, 0) > 0) THEN
         IF (COALESCE(NEW.PERCREDUCAOBC, 0) > 0) THEN
            SET NEW.VALORBCICMS = NEW.VALORLIQUIDO * (1 - (NEW.PERCREDUCAOBC / 100));
         ELSE
            SET NEW.VALORBCICMS = NEW.VALORLIQUIDO;
         END IF;
         SET NEW.VALORICMS = (NEW.VALORBCICMS * COALESCE(NEW.PERCICMS, 0)) / 100;
      END IF;
   END IF;
   
   IF ((NEW.CFOP = '5933') AND (NEW.CSOSN IS NULL)) THEN
      IF (COALESCE(NEW.VALORALIQUOTAISSQN, 0) > 0) THEN
         SET NEW.VALORBCISSQN = NEW.VALORLIQUIDO;
         SET NEW.VALORISSQN = (NEW.VALORBCISSQN * COALESCE(NEW.VALORALIQUOTAISSQN, 0)) / 100;
      END IF;
   END IF;
   
   IF (EXCLUIBCPISCOFINS <> '1') THEN
      SET NEW.VALORBCPIS = NEW.VALORLIQUIDO;
      SET NEW.VALORPIS = (NEW.VALORBCPIS * COALESCE(NEW.PERCPIS, 0)) / 100;
      SET NEW.VALORBCCOFINS = NEW.VALORLIQUIDO;
      SET NEW.VALORCOFINS = (NEW.VALORBCCOFINS * COALESCE(NEW.PERCCOFINS, 0)) / 100;
   END IF;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.BI_TANTECIPACAOCARTAO_CONTROLE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER BI_TANTECIPACAOCARTAO_CONTROLE
BEFORE INSERT ON TANTECIPACAOCARTAO
FOR EACH ROW
BEGIN
  IF NEW.CONTROLE IS NULL THEN
    SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TANTECIPACAOCARTAO');
  END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TANEXOOS_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TANEXOOS_BI BEFORE INSERT ON TANEXOOS
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TANEXOOS' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TCENTROCUSTO_AU0
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TCENTROCUSTO_AU0 AFTER UPDATE ON tcentrocusto FOR EACH ROW BEGIN
IF NEW.CENTROCUSTO <> OLD.CENTROCUSTO THEN
        UPDATE TUSUARIO 
        SET CENTROCUSTO = NEW.CENTROCUSTO 
        WHERE CODCENTROCUSTO = OLD.CONTROLE;
    END IF;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.THISTORICOOS_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER THISTORICOOS_BI BEFORE INSERT ON THISTORICOOS
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='THISTORICOOS' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOFICINACHECKLIST_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOFICINACHECKLIST_BI BEFORE INSERT ON TOFICINACHECKLIST
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TOFICINACHECKLIST' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOFICINAIMAGEMVEICULO_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOFICINAIMAGEMVEICULO_BI BEFORE INSERT ON TOFICINAIMAGEMVEICULO
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TOFICINAIMAGEMVEICULO' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOFICINAITEMCHECKLIST_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOFICINAITEMCHECKLIST_BI BEFORE INSERT ON TOFICINAITEMCHECKLIST
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TOFICINAITEMCHECKLIST' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOFICINALOCALIZACAOVEICULO_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOFICINALOCALIZACAOVEICULO_BI BEFORE INSERT ON TOFICINALOCALIZACAOVEICULO
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables WHERE table_name='TOFICINALOCALIZACAOVEICULO' AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOFICINAVEICULO_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOFICINAVEICULO_BI BEFORE INSERT ON TOFICINAVEICULO
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TOFICINAVEICULO' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOSCHECKLIST_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOSCHECKLIST_BI BEFORE INSERT ON TOSCHECKLIST
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TOSCHECKLIST' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOSOFICINA_BI
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOSOFICINA_BI BEFORE INSERT ON TOSOFICINA
FOR EACH ROW
BEGIN
    IF NEW.CONTROLE IS NULL THEN
        SET NEW.CONTROLE = (SELECT AUTO_INCREMENT FROM information_schema.tables 
                            WHERE table_name='TOSOFICINA' 
                              AND table_schema=DATABASE());
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Copiando estrutura para trigger basesgmasteralpes.TOS_CRIAHISTORICOOS
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER TOS_CRIAHISTORICOOS AFTER UPDATE ON TOS
FOR EACH ROW
BEGIN
    IF NEW.SITUACAO <> OLD.SITUACAO THEN
        INSERT INTO THISTORICOOS (CODOS, SITUACAOANTIGA, SITUACAONOVA)
        VALUES (NEW.CONTROLE, OLD.SITUACAO, NEW.SITUACAO);
    END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
